mm: memory.c: Temp fix compiling error
Introduced merging tag v3.10.76

* error: implicit declaration of function 'check_stack_guard_page' [-Werror=implicit-function-declaration]